In [1]:
import torch

In [3]:
def activation(x):
    return 1/(1+torch.exp(-x))

## Implementing 1-layer neural network

In [4]:
torch.manual_seed(7)

features = torch.randn((1, 5))
weights = torch.randn_like(features)
bias = torch.randn((1, 1))

In [9]:
output = activation(torch.sum(features * weights) + bias)
output

tensor([[0.1595]])

In [11]:
output = activation(torch.sum(torch.mm(features, weights.view(5, 1))) + bias)
output

tensor([[0.1595]])

## Implementing 2-layer neural network

In [39]:
torch.manual_seed(7)

features = torch.randn((1, 3))
n_input = features.shape[1]
n_hidden = 2
n_output = 1

W1 = torch.randn((n_input, n_hidden))
W2 = torch.randn((n_hidden, n_output))

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
output

tensor([[0.3171]])

### Numpy to Torch

In [43]:
import numpy as np

a = np.random.randn(4, 3)
a

array([[-0.01019559,  0.08307015,  0.19992114],
       [-1.20082019,  1.44131263,  1.11893384],
       [ 0.52214463,  1.2965419 ,  0.19599156],
       [-0.63863521,  0.94334061,  0.64618643]])

In [44]:
b = torch.from_numpy(a)
b

tensor([[-0.0102,  0.0831,  0.1999],
        [-1.2008,  1.4413,  1.1189],
        [ 0.5221,  1.2965,  0.1960],
        [-0.6386,  0.9433,  0.6462]], dtype=torch.float64)

### Torch to Numpy

In [47]:
b.numpy()

array([[-0.01019559,  0.08307015,  0.19992114],
       [-1.20082019,  1.44131263,  1.11893384],
       [ 0.52214463,  1.2965419 ,  0.19599156],
       [-0.63863521,  0.94334061,  0.64618643]])

Memory is shared!

In [49]:
b.mul_(2)
print(b)
a

tensor([[-0.0408,  0.3323,  0.7997],
        [-4.8033,  5.7653,  4.4757],
        [ 2.0886,  5.1862,  0.7840],
        [-2.5545,  3.7734,  2.5847]], dtype=torch.float64)


array([[-0.04078234,  0.33228061,  0.79968457],
       [-4.80328078,  5.76525053,  4.47573536],
       [ 2.08857854,  5.18616761,  0.78396626],
       [-2.55454085,  3.77336244,  2.58474573]])